# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: "/#about"
    weight: 1
  - name: People
    url: "/#people"
    weight: 2
  - name: Collaborators
    weight: 3
    url: "/#collaborators"
  - name: Publications
    url: "/#publications"
    weight: 4


